### ISSUE TITLE
"Rainbow" Test Mode

### ISSUE THREAD

**Issue by vlx200** [Pixelcontroller/f16v5_issues#8] opened 2024-10-11 17:53 UTC
Each time I select "Rainbow" test mode the controller seems to stop responding to the push buttons on the PCBA. The test mode activates and the lights continue to display the pattern but no response to the push buttons. In order to get out of this state I have to power cycle the controller.

**Comment by keithsw1111** [comment] 2024-10-13 05:17
Can you email us support at pixelcontroller.com

I want to check your build and maybe send you the latest test firmware as i could not reproduce this using my latest builds.

**Comment by vlx200** [comment] 2024-10-13 14:36
Hi Keith,Happy to help. The GUI on the controller indicates Bld:32What additional information would help to characterize the anomaly?On Oct 13, 2024, at 1:17 AM, Keith Westley ***@***.***> wrote:﻿
Can you email us support at pixelcontroller.com
I want to check your build and maybe send you the latest test firmware as i could not reproduce this using my latest builds.

**Comment by keithsw1111** [comment] 2024-10-13 17:01
Can you email us ... responding to this notification by email is not the same thing. I cant send you a test if you dont.

**Comment by vlx200** [comment] 2024-10-13 20:12
I added support in the “To”. Is that not the right email address? On Oct 13, 2024, at 1:01 PM, Keith Westley ***@***.***> wrote:﻿
Can you email us ... responding to this notification by email is not the same thing. I cant send you a test if you dont.

**Comment by keithsw1111** [comment] 2024-10-16 08:36
Will be fixed in build 33

**Closed by keithsw1111** 2024-10-16 08:36 UTC
